import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { useParams } from "react-router-dom";
import Breadcrumbs from "../components/navigation/Breadcrumbs";
import SectionLabel from "../components/common/SectionLabel";
import SubjectRow from "../components/archive/SubjectRow";
import EmptyState from "../components/common/EmptyState";
import { courses, subjects } from "../data/mockData";
export default function Subjects(){const {departmentSlug,courseSlug,semesterNumber}=useParams();const course=courses.find(item=>item.slug===courseSlug);const [query,setQuery]=useState("");const semesterSubjects=useMemo(()=>{const normalized=query.trim().toLowerCase();return subjects.filter(subject=>String(subject.semester)===String(semesterNumber)&&(!normalized||subject.name.toLowerCase().includes(normalized)||subject.code.toLowerCase().includes(normalized)))},[query,semesterNumber]);return <section className="min-h-[75vh] px-5 py-12 lg:px-8 lg:py-20"><div className="mx-auto max-w-[1500px]"><Breadcrumbs items={[{label:departmentSlug,to:`/${departmentSlug}`},{label:course?.shortName||courseSlug,to:`/${departmentSlug}/${courseSlug}`},{label:`SEM ${semesterNumber}`}]}/><div className="mt-16 grid gap-10 lg:grid-cols-[1fr_420px] lg:items-end"><div><SectionLabel number="04">SEMESTER {semesterNumber}</SectionLabel><h1 className="display mt-5 text-[clamp(5rem,12vw,11rem)] leading-[.78]">SUBJECT<br/><span className="text-transparent" style={{WebkitTextStroke:"3px #090909"}}>ARCHIVE.</span></h1></div><div><label className="mono mb-2 block text-[10px] font-bold uppercase tracking-[0.15em]">SEARCH SUBJECT / CODE</label><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2" size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} className="focus-ring brutal-border w-full bg-acid py-4 pl-12 pr-12 font-bold uppercase outline-none" placeholder="E.G. NETWORKS"/>{query&&<button onClick={()=>setQuery("")} className="absolute right-3 top-1/2 -translate-y-1/2" aria-label="Clear search"><X size={19}/></button>}</div><div className="mono mt-3 flex items-center gap-2 text-[9px] uppercase text-black/55"><SlidersHorizontal size={13}/> {semesterSubjects.length} subjects found</div></div></div><div className="mt-16">{semesterSubjects.length?semesterSubjects.map((subject,index)=><SubjectRow key={subject.id} subject={subject} index={index}/>):<EmptyState title="No subjects found" description="Try another subject name or subject code."/>}</div></div></section>}
